version: '3.10'

services:
  django:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15.7-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./database:/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
